### ISSUE TITLE
missing dependences due asumming winlinux distros

### ISSUE THREAD

**Issue by mckaygerhard** [cat-in-136/FlatSurfacesTheme#2]
i just downloaded and try to used and falback to default event apply the changed theme, SEEMS NEED gtk2-engines-pixbuf AND gtk2-engines PACKAGES

```
(lxappearance:26049): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «hcengine»,
(lxappearance:26049): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «pixmap»,
```

**Comment by cat-in-136** [comment]
Yes, please install these gtk2 theme packages and use gtk2 apps.

**Comment by mckaygerhard** [comment]
err i mean please "point that in README" i can do by you in a pull request!

**Comment by cat-in-136** [comment]
47f8f38
