### ISSUE TITLE
xfce4-panel don't show windows buttons

### ISSUE THREAD

**Issue by Programmist11180** [cat-in-136/FlatSurfacesTheme#5]
xfce4-panel with Flat Surfaces Theme don't show window buttons for programs launched after applying theme.
![flat](https://user-images.githubusercontent.com/4720307/163975734-dd734950-a151-40d7-b084-6de4a8c1314d.png)

With other GTK3 theme window buttons always shows correctly.
![norm](https://user-images.githubusercontent.com/4720307/163975742-8813f9de-a9a7-42c9-a15a-6c586a71588d.png)

In file  .xsession-errors I found some errors
`(xfce4-panel:2956): libtasklist-CRITICAL **: 11:50:37.891: tasklist-widget.c:1155 (xfce_tasklist_size_allocate): expression 'area.height == tasklist->size' failed.`

Version:
libgtk-3-0:  3.24.33-1
xfce4-panel:  4.16.3-1
FlatSurfaces:  0.7

**Comment by cat-in-136** [comment]
@Programmist11180  I could not reproduce the issue:

OS Image: debian-live-11.3.0-amd64-xfce.iso
libgtk-3-0: 3.24.24-4+deb11u2
xfce4-panel: 4.16.2-1
FlatSurfaces: 0.7

![VirtualBox_debian_20_04_2022_22_13_11](https://user-images.githubusercontent.com/379009/164238559-d0c9e94b-12cf-423a-82cc-1cb5a16a0974.png)

**Comment by Programmist11180** [comment]
Seems, this is a bug of xfce4-panel
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004837
https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/188

**Comment by Tamaranch** [comment]
@cat-in-136 You have to restart the panel or open/close a window to realize the problem. This is reproducible with panel 4.16.x and probably earlier versions.

NB: https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/645#note_56111

**Comment by Programmist11180** [comment]
Hello. Last few weeks I use theme FlatSurfaces 0.8 with xfce4-panel 4.19 . Problem no more appears.
